In [1]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/data

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\data

In [2]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "가구/인테리어", "param": [ "50000004"]},
      {"name": "도서", "param": [ "50005542"]},
      #{"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "생활/건강", "param": [ "50000008"]},
      {"name": "스포츠/레저", "param": [ "50000007"]},
      {"name": "식품", "param": [ "50000006"]},
      {"name": "출산/육아", "param": [ "50000005"]},
      #{"name": "패션의류", "param": [ "50000000"]},
      {"name": "패션잡화", "param": [ "50000001"]},
      {"name": "화장품/미용", "param": [ "50000002"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_b = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_1 = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_1 = pd.merge(df_all_1, df, left_on="period", right_on="period")
##
df_all_1

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용
period,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522
...,...,...,...,...,...,...,...,...,...,...
2023-06-29,7.64771,7.65642,4.10965,0.94139,10.81814,6.14819,5.72676,3.27358,7.96113,2.62158
2023-06-30,6.91899,6.65691,3.52852,0.94736,9.42761,5.25181,4.82366,2.79876,6.70173,2.28731
2023-07-01,7.02520,7.85120,3.71108,0.84828,8.84696,5.66207,4.57256,2.91360,7.48994,2.44349
2023-07-02,7.87369,9.10097,4.47432,0.92346,10.04731,7.00957,5.24558,3.41250,8.36579,2.76642
2023-07-03,8.89885,8.21887,4.54340,1.14224,11.77047,7.24405,6.18798,3.73485,7.72387,2.99459

In [3]:
df_all_1['유형']='PC+MO'
df_all_1['성별']='전체'
df_all_1['연령']='전체'
df_all_1

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,7.64771,7.65642,4.10965,0.94139,10.81814,6.14819,5.72676,3.27358,7.96113,2.62158,PC+MO,전체,전체
2023-06-30,6.91899,6.65691,3.52852,0.94736,9.42761,5.25181,4.82366,2.79876,6.70173,2.28731,PC+MO,전체,전체
2023-07-01,7.02520,7.85120,3.71108,0.84828,8.84696,5.66207,4.57256,2.91360,7.48994,2.44349,PC+MO,전체,전체
2023-07-02,7.87369,9.10097,4.47432,0.92346,10.04731,7.00957,5.24558,3.41250,8.36579,2.76642,PC+MO,전체,전체
2023-07-03,8.89885,8.21887,4.54340,1.14224,11.77047,7.24405,6.18798,3.73485,7.72387,2.99459,PC+MO,전체,전체

In [4]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"pc",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_c = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_d = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_2 = pd.merge(df_c, df_d, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_2 = pd.merge(df_all_2, df, left_on="period", right_on="period")
##
df_all_2

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용
period,,,,,,,,,,
2021-05-10,14.63792,6.80318,4.56235,0.01630,13.32898,6.15700,5.14222,2.25838,7.10373,2.44471
2021-05-11,14.07345,6.76884,4.30723,0.05581,12.83981,5.76095,4.70466,2.17277,7.00891,2.37549
2021-05-12,14.02036,6.89187,4.13999,0.06655,12.41209,5.44190,4.72175,2.12924,6.89565,2.21969
2021-05-13,13.77661,6.95908,3.94519,0.06178,12.05265,5.24650,4.62933,2.11499,6.68492,2.22041
2021-05-14,13.28626,6.64611,3.58689,0.05526,10.96485,4.78608,4.44814,1.94159,6.28395,2.16801
...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.65297,4.12691,3.15506,0.76944,9.32292,4.43667,3.74239,1.27969,4.42996,1.37538
2023-06-30,5.84910,3.15696,2.48612,0.94859,7.55224,3.54037,2.97553,1.01251,3.30190,1.06836
2023-07-01,3.52906,1.92329,1.27306,0.65997,3.33134,1.89509,1.53663,0.42398,1.88732,0.50783
2023-07-02,3.82058,2.24314,1.51720,0.70198,3.65930,2.22264,1.74874,0.47545,2.15718,0.60579
2023-07-03,8.11753,4.22028,3.48065,1.17266,10.33848,5.28661,4.17249,1.50469,4.21418,1.64082

In [5]:
df_all_2['유형']='PC'
df_all_2['성별']='전체'
df_all_2['연령']='전체'
df_all_2

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,14.63792,6.80318,4.56235,0.01630,13.32898,6.15700,5.14222,2.25838,7.10373,2.44471,PC,전체,전체
2021-05-11,14.07345,6.76884,4.30723,0.05581,12.83981,5.76095,4.70466,2.17277,7.00891,2.37549,PC,전체,전체
2021-05-12,14.02036,6.89187,4.13999,0.06655,12.41209,5.44190,4.72175,2.12924,6.89565,2.21969,PC,전체,전체
2021-05-13,13.77661,6.95908,3.94519,0.06178,12.05265,5.24650,4.62933,2.11499,6.68492,2.22041,PC,전체,전체
2021-05-14,13.28626,6.64611,3.58689,0.05526,10.96485,4.78608,4.44814,1.94159,6.28395,2.16801,PC,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.65297,4.12691,3.15506,0.76944,9.32292,4.43667,3.74239,1.27969,4.42996,1.37538,PC,전체,전체
2023-06-30,5.84910,3.15696,2.48612,0.94859,7.55224,3.54037,2.97553,1.01251,3.30190,1.06836,PC,전체,전체
2023-07-01,3.52906,1.92329,1.27306,0.65997,3.33134,1.89509,1.53663,0.42398,1.88732,0.50783,PC,전체,전체
2023-07-02,3.82058,2.24314,1.51720,0.70198,3.65930,2.22264,1.74874,0.47545,2.15718,0.60579,PC,전체,전체
2023-07-03,8.11753,4.22028,3.48065,1.17266,10.33848,5.28661,4.17249,1.50469,4.21418,1.64082,PC,전체,전체

In [6]:
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"mo",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_e = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_f = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_3 = pd.merge(df_e, df_f, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_3 = pd.merge(df_all_3, df, left_on="period", right_on="period")
##
df_all_3

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용
period,,,,,,,,,,
2021-05-10,8.42057,8.23817,4.39991,0.04131,10.72849,5.91185,5.27104,4.81846,8.54113,2.76174
2021-05-11,7.75628,8.11274,3.97396,0.09492,10.18976,5.54613,5.23993,4.53433,8.27317,2.63119
2021-05-12,7.67921,8.33854,3.86745,0.10342,9.96471,5.40221,4.87689,4.56601,8.26797,2.55108
2021-05-13,7.62695,8.40903,3.64492,0.09643,9.39719,5.16809,4.54110,4.62414,8.01062,2.39082
2021-05-14,7.46103,8.02568,3.41260,0.08705,8.79650,4.71180,4.01556,4.35211,7.64592,2.21510
...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.09491,6.91048,3.40928,0.76605,8.64973,5.19087,4.95958,3.10937,7.14120,2.37819
2023-06-30,5.56838,6.14597,2.99829,0.71528,7.72059,4.51368,4.23385,2.68440,6.14787,2.11697
2023-07-01,6.42298,7.82308,3.58162,0.70093,8.44374,5.47964,4.42325,2.99564,7.44636,2.46370
2023-07-02,7.24172,9.06400,4.32389,0.76831,9.62897,6.82313,5.07879,3.51533,8.30141,2.77946
2023-07-03,6.97197,7.48509,3.77148,0.85319,9.34898,6.09722,5.31795,3.53325,6.95511,2.69432

In [11]:
df_all_3['유형']='MO'
df_all_3['성별']='전체'
df_all_3['연령']='전체'
df_all_3

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,8.42057,8.23817,4.39991,0.04131,10.72849,5.91185,5.27104,4.81846,8.54113,2.76174,MO,전체,전체
2021-05-11,7.75628,8.11274,3.97396,0.09492,10.18976,5.54613,5.23993,4.53433,8.27317,2.63119,MO,전체,전체
2021-05-12,7.67921,8.33854,3.86745,0.10342,9.96471,5.40221,4.87689,4.56601,8.26797,2.55108,MO,전체,전체
2021-05-13,7.62695,8.40903,3.64492,0.09643,9.39719,5.16809,4.54110,4.62414,8.01062,2.39082,MO,전체,전체
2021-05-14,7.46103,8.02568,3.41260,0.08705,8.79650,4.71180,4.01556,4.35211,7.64592,2.21510,MO,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.09491,6.91048,3.40928,0.76605,8.64973,5.19087,4.95958,3.10937,7.14120,2.37819,MO,전체,전체
2023-06-30,5.56838,6.14597,2.99829,0.71528,7.72059,4.51368,4.23385,2.68440,6.14787,2.11697,MO,전체,전체
2023-07-01,6.42298,7.82308,3.58162,0.70093,8.44374,5.47964,4.42325,2.99564,7.44636,2.46370,MO,전체,전체
2023-07-02,7.24172,9.06400,4.32389,0.76831,9.62897,6.82313,5.07879,3.51533,8.30141,2.77946,MO,전체,전체
2023-07-03,6.97197,7.48509,3.77148,0.85319,9.34898,6.09722,5.31795,3.53325,6.95511,2.69432,MO,전체,전체

In [16]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"",
  "gender":"f",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_g = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_h = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_4 = pd.merge(df_g, df_h, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_4 = pd.merge(df_all_4, df, left_on="period", right_on="period")
##
df_all_4['유형']='PC+MO'
df_all_4['성별']='여성'
df_all_4['연령']='전체'
df_all_4

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,16.55800,27.64650,14.02977,0.14356,28.00930,10.27756,15.85785,17.75772,26.63597,9.60420,PC+MO,여성,전체
2021-05-11,15.03444,27.35482,12.79520,0.34058,26.49824,9.71759,15.35641,16.89082,25.83790,9.13483,PC+MO,여성,전체
2021-05-12,14.75753,28.24063,12.43780,0.37073,25.68103,9.40168,14.18681,17.14215,26.09220,8.80259,PC+MO,여성,전체
2021-05-13,14.91247,28.49789,11.73532,0.33902,24.20274,9.15342,13.12004,17.48006,25.49049,8.23622,PC+MO,여성,전체
2021-05-14,14.51323,27.17280,10.89395,0.30529,22.32649,8.27510,11.39316,16.39737,24.32614,7.58125,PC+MO,여성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,12.60990,25.26904,10.63868,2.37959,22.19146,9.71681,14.88352,11.73980,24.20660,8.73876,PC+MO,여성,전체
2023-06-30,11.16195,22.28117,9.19833,2.20636,19.29062,8.33480,12.52338,9.96505,20.47869,7.67987,PC+MO,여성,전체
2023-07-01,12.27861,27.15242,10.37930,1.98346,19.92257,9.89914,12.37045,10.14339,23.63355,8.48481,PC+MO,여성,전체
2023-07-02,13.82246,31.14915,12.31941,2.16070,22.90080,12.36827,14.08985,11.83471,25.99295,9.46461,PC+MO,여성,전체
2023-07-03,14.16722,27.03136,11.45696,2.63936,23.77253,11.72501,15.84659,13.18488,23.09616,9.70070,PC+MO,여성,전체

In [20]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"",
  "gender":"m",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_9 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_10 = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_5 = pd.merge(df_9, df_10, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_5 = pd.merge(df_all_5, df, left_on="period", right_on="period")
##
df_all_5['유형']='PC+MO'
df_all_5['성별']='남성'
df_all_5['연령']='전체'
df_all_5

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,68.43042,32.13717,21.91026,0.12880,69.92240,62.11278,24.78164,11.80036,40.78190,8.25534,PC+MO,남성,전체
2021-05-11,61.54289,31.25785,19.56926,0.28832,65.93767,57.83387,23.59068,10.50914,38.87363,7.53003,PC+MO,남성,전체
2021-05-12,60.40445,31.78704,18.82833,0.31855,64.45869,55.99312,22.42854,10.02181,37.91723,7.18339,PC+MO,남성,전체
2021-05-13,58.75912,31.99911,17.51657,0.30305,60.67920,52.76316,20.91622,9.65310,35.86615,6.68173,PC+MO,남성,전체
2021-05-14,56.78391,29.99193,15.97337,0.25837,54.81206,47.62322,18.19879,8.95314,33.53058,5.94637,PC+MO,남성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,53.24537,23.94672,19.10101,4.14526,65.90705,53.46070,26.48987,7.99987,32.10428,7.69748,PC+MO,남성,전체
2023-06-30,48.11210,20.56691,16.55931,3.81280,58.25008,45.91740,22.26360,7.08579,27.45000,6.85332,PC+MO,남성,전체
2023-07-01,50.24752,24.78372,17.55087,3.65983,54.58898,49.32753,21.97754,8.82458,31.31701,7.40572,PC+MO,남성,전체
2023-07-02,56.18875,30.03970,21.21272,4.08132,61.28124,60.70512,25.72909,10.73815,36.39920,8.72900,PC+MO,남성,전체
2023-07-03,61.92676,27.02610,21.44412,4.70143,71.55586,61.93812,30.07238,9.80435,32.93800,9.52839,PC+MO,남성,전체

In [24]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"pc",
  "gender":"f",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_11 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_12 = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_6 = pd.merge(df_11, df_12, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_6 = pd.merge(df_all_6, df, left_on="period", right_on="period")
##
df_all_6['유형']='PC'
df_all_6['성별']='여성'
df_all_6['연령']='전체'
df_all_6

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,55.22339,60.52173,45.52744,0.17598,73.88807,28.02866,43.82306,27.01428,54.60996,21.20520,PC,여성,전체
2021-05-11,51.63805,61.84594,42.14717,0.64756,72.11363,27.00182,41.37822,26.43617,54.21554,20.32912,PC,여성,전체
2021-05-12,50.41533,63.29658,40.84788,0.79624,68.66532,25.46808,39.77830,26.25691,53.45669,19.66790,PC,여성,전체
2021-05-13,50.96051,63.37878,38.67133,0.74579,65.60158,25.57107,36.27576,25.58858,52.55479,18.49297,PC,여성,전체
2021-05-14,47.54195,59.11590,33.86980,0.67338,56.82703,21.68182,30.08769,22.99683,47.27931,15.57388,PC,여성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,46.58248,74.35800,41.33341,8.76259,71.16959,32.16037,44.77719,23.00218,71.17033,22.48668,PC,여성,전체
2023-06-30,38.20154,58.91617,31.33029,7.69538,57.18630,24.98879,34.19536,17.38451,53.30147,17.48096,PC,여성,전체
2023-07-01,16.05110,34.41112,13.56501,3.55537,21.83345,10.26190,13.08245,5.88446,28.54624,7.75800,PC,여성,전체
2023-07-02,18.03593,39.43790,17.02601,4.13705,26.60699,12.55123,15.11537,7.14872,32.30906,8.59343,PC,여성,전체
2023-07-03,53.64870,75.64778,42.23561,9.63659,78.16971,38.81200,51.18576,26.24860,67.05791,24.97158,PC,여성,전체

In [25]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"pc",
  "gender":"m",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_13 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_14 = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_7 = pd.merge(df_13, df_14, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_7 = pd.merge(df_all_7, df, left_on="period", right_on="period")
##
df_all_7['유형']='PC'
df_all_7['성별']='남성'
df_all_7['연령']='전체'
df_all_7

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,88.04638,25.07879,26.50503,0.08634,85.36696,57.22420,27.52748,9.35221,31.24578,7.98950,PC,남성,전체
2021-05-11,77.44136,23.84732,24.25621,0.27885,79.35605,52.43359,25.36365,8.11068,28.83509,7.20190,PC,남성,전체
2021-05-12,75.81826,24.28654,22.93974,0.33846,76.94452,49.35798,24.17076,7.55478,27.85243,7.00173,PC,남성,전체
2021-05-13,73.97548,24.87983,21.32580,0.32555,72.41242,46.05607,22.46958,7.12862,26.18218,6.48473,PC,남성,전체
2021-05-14,68.82313,22.39540,18.72470,0.26143,61.03986,40.41540,18.77290,6.47181,24.24014,5.49741,PC,남성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,61.51522,21.35764,22.02946,4.15857,78.16416,49.55004,27.73125,6.49133,28.70730,8.08230,PC,남성,전체
2023-06-30,52.94924,16.53805,17.88124,3.62249,64.75960,39.70679,21.89672,5.41452,22.36883,6.76613,PC,남성,전체
2023-07-01,30.63823,12.04011,9.88288,2.24912,32.52788,21.46755,12.78100,2.51115,14.64947,4.00511,PC,남성,전체
2023-07-02,33.84853,14.93222,11.89505,2.48427,36.65166,25.43963,15.38255,3.05068,17.05445,5.10970,PC,남성,전체
2023-07-03,73.75850,24.24419,25.74296,4.76072,87.69942,59.40890,33.83652,8.25018,30.22363,10.64150,PC,남성,전체

In [29]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"mo",
  "gender":"f",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_15 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_16 = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_8 = pd.merge(df_15, df_16, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_8 = pd.merge(df_all_8, df, left_on="period", right_on="period")
##
df_all_8['유형']='MO'
df_all_8['성별']='여성'
df_all_8['연령']='전체'
df_all_8

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,15.04493,26.07765,12.78593,0.13959,25.34009,9.52723,14.68272,17.10844,25.23628,9.05374,MO,여성,전체
2021-05-11,13.61539,25.74321,11.64190,0.32421,23.88524,8.99302,14.25044,16.25085,24.44262,8.60643,MO,여성,전체
2021-05-12,13.37282,26.59352,11.32040,0.35016,23.19721,8.72049,13.11819,16.50996,24.72223,8.29104,MO,여성,전체
2021-05-13,13.51275,26.85072,10.67708,0.31967,21.82661,8.46679,12.14723,16.87124,24.14212,7.75486,MO,여성,전체
2021-05-14,13.21306,25.64198,9.97290,0.28781,20.28099,7.69773,10.59111,15.85669,23.12625,7.18194,MO,여성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,11.32082,23.25968,9.48967,2.13717,19.57540,8.83634,13.67038,11.15513,22.28359,8.14144,MO,여성,전체
2023-06-30,10.11251,20.71036,8.33807,1.99457,17.20230,7.65805,11.60783,9.53345,19.06060,7.22385,MO,여성,전체
2023-07-01,11.90908,26.36800,10.06702,1.89468,19.24343,9.68217,12.09150,10.06101,22.99326,8.33020,MO,여성,전체
2023-07-02,13.40747,30.25043,11.92080,2.05600,22.06020,12.10535,13.76564,11.73003,25.26115,9.29398,MO,여성,전체
2023-07-03,12.67924,24.99961,10.28839,2.37298,20.89350,10.66243,14.44885,12.51570,21.28698,9.03733,MO,여성,전체

In [30]:
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"mo",
  "gender":"m",
  "ages":[]
}
## 데이터 정제 및 merge 파트

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_17 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_18 = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_9 = pd.merge(df_17, df_18, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_9 = pd.merge(df_all_9, df, left_on="period", right_on="period")
##
df_all_9['유형']='MO'
df_all_9['성별']='남성'
df_all_9['연령']='전체'
df_all_9

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,61.28217,32.80897,20.03897,0.13500,64.53617,61.24372,23.27204,12.01148,41.77780,8.04477,MO,남성,전체
2021-05-11,55.54574,32.04629,17.75353,0.28102,61.15977,57.23478,22.36185,10.75119,40.05783,7.35917,MO,남성,전체
2021-05-12,54.56543,32.58004,17.17992,0.30296,59.95405,55.76143,21.24624,10.29716,39.13995,6.98787,MO,남성,전체
2021-05-13,53.02408,32.69062,15.98689,0.28734,56.44408,52.65743,19.83131,9.95501,37.06325,6.50681,MO,남성,전체
2021-05-14,51.90170,30.86881,14.75731,0.24897,52.13589,47.81355,17.44733,9.26781,34.70843,5.85846,MO,남성,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,49.41499,23.78608,17.73639,4.00318,61.43511,52.63917,25.29560,8.10557,31.87057,7.34448,MO,남성,전체
2023-06-30,45.30357,20.87594,15.67757,3.73227,55.43469,45.91793,21.60906,7.26238,27.78915,6.64546,MO,남성,전체
2023-07-01,53.42078,27.10946,18.86197,3.88661,59.35635,54.57458,23.51893,10.09243,34.39565,7.99982,MO,남성,전체
2023-07-02,59.83932,32.77480,22.80971,4.34012,66.59728,67.40496,27.42964,12.28217,39.97060,9.33295,MO,남성,전체
2023-07-03,56.92375,26.81011,19.66172,4.52934,65.95486,60.49071,28.13350,9.86094,32.50735,8.93376,MO,남성,전체

In [31]:
df_list=[df_all_1,df_all_2,df_all_3,df_all_4,df_all_5,df_all_6,df_all_7,df_all_8,df_all_9]

In [32]:
df_all=pd.concat(df_list)
df_all

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,49.41499,23.78608,17.73639,4.00318,61.43511,52.63917,25.29560,8.10557,31.87057,7.34448,MO,남성,전체
2023-06-30,45.30357,20.87594,15.67757,3.73227,55.43469,45.91793,21.60906,7.26238,27.78915,6.64546,MO,남성,전체
2023-07-01,53.42078,27.10946,18.86197,3.88661,59.35635,54.57458,23.51893,10.09243,34.39565,7.99982,MO,남성,전체
2023-07-02,59.83932,32.77480,22.80971,4.34012,66.59728,67.40496,27.42964,12.28217,39.97060,9.33295,MO,남성,전체
2023-07-03,56.92375,26.81011,19.66172,4.52934,65.95486,60.49071,28.13350,9.86094,32.50735,8.93376,MO,남성,전체

In [33]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7065 entries, 2021-05-10 to 2023-07-03
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   디지털/가전   7065 non-null   float64
 1   패션의류     7065 non-null   float64
 2   가구/인테리어  7065 non-null   float64
 3   도서       7065 non-null   float64
 4   생활/건강    7065 non-null   float64
 5   스포츠/레저   7065 non-null   float64
 6   식품       7065 non-null   float64
 7   출산/육아    7065 non-null   float64
 8   패션잡화     7065 non-null   float64
 9   화장품/미용   7065 non-null   float64
 10  유형       7065 non-null   object
 11  성별       7065 non-null   object
 12  연령       7065 non-null   object
dtypes: float64(10), object(3)
memory usage: 772.7+ KB

In [34]:
## 엑셀에 저장
df_all.to_excel("LCLS_all_fm_all.xlsx", sheet_name="click ratio")
df_all.head()

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체