In [1]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/data

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\data

In [2]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "가구/인테리어", "param": [ "50000004"]},
      {"name": "도서", "param": [ "50005542"]},
      #{"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "생활/건강", "param": [ "50000008"]},
      {"name": "스포츠/레저", "param": [ "50000007"]},
      {"name": "식품", "param": [ "50000006"]},
      {"name": "출산/육아", "param": [ "50000005"]},
      #{"name": "패션의류", "param": [ "50000000"]},
      {"name": "패션잡화", "param": [ "50000001"]},
      {"name": "화장품/미용", "param": [ "50000002"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_b = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_1 = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_1 = pd.merge(df_all_1, df, left_on="period", right_on="period")
##
df_all_1

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용
period,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522
...,...,...,...,...,...,...,...,...,...,...
2023-06-29,7.64771,7.65642,4.10965,0.94139,10.81814,6.14819,5.72676,3.27358,7.96113,2.62158
2023-06-30,6.91899,6.65691,3.52852,0.94736,9.42761,5.25181,4.82366,2.79876,6.70173,2.28731
2023-07-01,7.02520,7.85120,3.71108,0.84828,8.84696,5.66207,4.57256,2.91360,7.48994,2.44349
2023-07-02,7.87369,9.10097,4.47432,0.92346,10.04731,7.00957,5.24558,3.41250,8.36579,2.76642
2023-07-03,8.89885,8.21887,4.54340,1.14224,11.77047,7.24405,6.18798,3.73485,7.72387,2.99459

In [3]:
df_all_1['유형']='PC+MO'
df_all_1['성별']='전체'
df_all_1['연령']='전체'
df_all_1

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,7.64771,7.65642,4.10965,0.94139,10.81814,6.14819,5.72676,3.27358,7.96113,2.62158,PC+MO,전체,전체
2023-06-30,6.91899,6.65691,3.52852,0.94736,9.42761,5.25181,4.82366,2.79876,6.70173,2.28731,PC+MO,전체,전체
2023-07-01,7.02520,7.85120,3.71108,0.84828,8.84696,5.66207,4.57256,2.91360,7.48994,2.44349,PC+MO,전체,전체
2023-07-02,7.87369,9.10097,4.47432,0.92346,10.04731,7.00957,5.24558,3.41250,8.36579,2.76642,PC+MO,전체,전체
2023-07-03,8.89885,8.21887,4.54340,1.14224,11.77047,7.24405,6.18798,3.73485,7.72387,2.99459,PC+MO,전체,전체

In [4]:
categories = [
      {"name": "가구/인테리어", "param": [ "50000004"]},
      {"name": "도서", "param": [ "50005542"]},
      #{"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "생활/건강", "param": [ "50000008"]},
      {"name": "스포츠/레저", "param": [ "50000007"]},
      {"name": "식품", "param": [ "50000006"]},
      {"name": "출산/육아", "param": [ "50000005"]},
      #{"name": "패션의류", "param": [ "50000000"]},
      {"name": "패션잡화", "param": [ "50000001"]},
      {"name": "화장품/미용", "param": [ "50000002"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "패션의류", "param": [ "50000000"]},
  ],
  "device":"pc",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_c = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_d = change_index(pd.DataFrame(results[1]["data"]), "패션의류")
##
df_all_2 = pd.merge(df_c, df_d, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_2 = pd.merge(df_all_2, df, left_on="period", right_on="period")
##
df_all_2

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용
period,,,,,,,,,,
2021-05-10,14.63792,6.80318,4.56235,0.01630,13.32898,6.15700,5.14222,2.25838,7.10373,2.44471
2021-05-11,14.07345,6.76884,4.30723,0.05581,12.83981,5.76095,4.70466,2.17277,7.00891,2.37549
2021-05-12,14.02036,6.89187,4.13999,0.06655,12.41209,5.44190,4.72175,2.12924,6.89565,2.21969
2021-05-13,13.77661,6.95908,3.94519,0.06178,12.05265,5.24650,4.62933,2.11499,6.68492,2.22041
2021-05-14,13.28626,6.64611,3.58689,0.05526,10.96485,4.78608,4.44814,1.94159,6.28395,2.16801
...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.65297,4.12691,3.15506,0.76944,9.32292,4.43667,3.74239,1.27969,4.42996,1.37538
2023-06-30,5.84910,3.15696,2.48612,0.94859,7.55224,3.54037,2.97553,1.01251,3.30190,1.06836
2023-07-01,3.52906,1.92329,1.27306,0.65997,3.33134,1.89509,1.53663,0.42398,1.88732,0.50783
2023-07-02,3.82058,2.24314,1.51720,0.70198,3.65930,2.22264,1.74874,0.47545,2.15718,0.60579
2023-07-03,8.11753,4.22028,3.48065,1.17266,10.33848,5.28661,4.17249,1.50469,4.21418,1.64082

In [5]:
df_all_2['유형']='PC'
df_all_2['성별']='전체'
df_all_2['연령']='전체'
df_all_2

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,14.63792,6.80318,4.56235,0.01630,13.32898,6.15700,5.14222,2.25838,7.10373,2.44471,PC,전체,전체
2021-05-11,14.07345,6.76884,4.30723,0.05581,12.83981,5.76095,4.70466,2.17277,7.00891,2.37549,PC,전체,전체
2021-05-12,14.02036,6.89187,4.13999,0.06655,12.41209,5.44190,4.72175,2.12924,6.89565,2.21969,PC,전체,전체
2021-05-13,13.77661,6.95908,3.94519,0.06178,12.05265,5.24650,4.62933,2.11499,6.68492,2.22041,PC,전체,전체
2021-05-14,13.28626,6.64611,3.58689,0.05526,10.96485,4.78608,4.44814,1.94159,6.28395,2.16801,PC,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.65297,4.12691,3.15506,0.76944,9.32292,4.43667,3.74239,1.27969,4.42996,1.37538,PC,전체,전체
2023-06-30,5.84910,3.15696,2.48612,0.94859,7.55224,3.54037,2.97553,1.01251,3.30190,1.06836,PC,전체,전체
2023-07-01,3.52906,1.92329,1.27306,0.65997,3.33134,1.89509,1.53663,0.42398,1.88732,0.50783,PC,전체,전체
2023-07-02,3.82058,2.24314,1.51720,0.70198,3.65930,2.22264,1.74874,0.47545,2.15718,0.60579,PC,전체,전체
2023-07-03,8.11753,4.22028,3.48065,1.17266,10.33848,5.28661,4.17249,1.50469,4.21418,1.64082,PC,전체,전체

In [6]:
df_all=pd.concat([df_all_1,df_all_2])
df_all

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,6.65297,4.12691,3.15506,0.76944,9.32292,4.43667,3.74239,1.27969,4.42996,1.37538,PC,전체,전체
2023-06-30,5.84910,3.15696,2.48612,0.94859,7.55224,3.54037,2.97553,1.01251,3.30190,1.06836,PC,전체,전체
2023-07-01,3.52906,1.92329,1.27306,0.65997,3.33134,1.89509,1.53663,0.42398,1.88732,0.50783,PC,전체,전체
2023-07-02,3.82058,2.24314,1.51720,0.70198,3.65930,2.22264,1.74874,0.47545,2.15718,0.60579,PC,전체,전체
2023-07-03,8.11753,4.22028,3.48065,1.17266,10.33848,5.28661,4.17249,1.50469,4.21418,1.64082,PC,전체,전체

In [7]:
## 엑셀에 저장
df_all.to_excel("LCLS_all_fm_all.xlsx", sheet_name="click ratio")
df_all.head()

,디지털/가전,패션의류,가구/인테리어,도서,생활/건강,스포츠/레저,식품,출산/육아,패션잡화,화장품/미용,유형,성별,연령
period,,,,,,,,,,,,,
2021-05-10,12.18344,9.68679,5.44947,0.04328,13.94238,7.33006,6.43235,5.15469,10.05799,3.29609,PC+MO,전체,전체
2021-05-11,11.39762,9.55987,4.97732,0.10491,13.29577,6.87210,6.27344,4.86485,9.78046,3.15404,PC+MO,전체,전체
2021-05-12,11.31013,9.80653,4.82853,0.11601,12.95931,6.64342,5.94068,4.88141,9.74198,3.03323,PC+MO,전체,전체
2021-05-13,11.18911,9.89209,4.56359,0.10808,12.32444,6.36751,5.60075,4.93127,9.43991,2.88430,PC+MO,전체,전체
2021-05-14,10.88907,9.44241,4.24099,0.09742,11.44237,5.80616,5.05788,4.62662,8.98145,2.70522,PC+MO,전체,전체