In [1]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/data

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\data

In [2]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
##종웅님 
headers = {"X-Naver-Client-Id": "EmdlUXsc4CuKNm_kxYKS",
           "X-Naver-Client-Secret":"dSLoIEmMgy"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

In [ ]:
devices=['','pc','mo']

## 대분류 카테고리 설정
for i in devices:
    categories = [
          {"name": "운동복", "param": [ "50000818"]},
          {"name": "상의", "param": [ "50000803"]},
          {"name": "세트", "param": [ "50000816"]},
          #{"name": "수영복/비치웨어", "param": [ "50004870"]},
          {"name": "아우터", "param": [ "50000806"]},
          {"name": "언더웨어", "param": [ "50000168"]},
          {"name": "잠옷/홈웨어", "param": [ "50000826"]},
          {"name": "하의", "param": [ "50000808"]},
          {"name": "한복", "param": [ "50000819"]},
          {"name": "파티복", "param": [ "50000820"]}
      ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
    data = {
    "startDate": "2021-05-10",
    "endDate": "2023-07-03",
    "timeUnit": "date",
    "category": [
      {"name": "패션의류", "param": [ "50000000"]},
      {"name": "원피스", "param": [ "50000807"]},
    ],
    "device":i,
    "gender":"",
    "ages":[]
    }
## 데이터 정제 및 merge 파트
    response = requests.post(url, headers=headers, json=data)

    results = response.json()["results"]


    df_1 = change_index(pd.DataFrame(results[0]["data"]), "패션/의류")
    df_2 = change_index(pd.DataFrame(results[1]["data"]), "원핏/매트")
##
    df_all_i = pd.merge(df_1, df_2, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
    for category in categories:
        if len(data["category"]) > 2:
            data["category"].pop(2)
        data["category"].append(category)

        result = requests.post(url, headers=headers, json=data)

        results = result.json()["results"]

        df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

        df_all_i = pd.merge(df_all_i, df, left_on="period", right_on="period")
    if i == "":
        df_all_1 = df_all_i
        df_all_1['유형']='PC+MO'
        df_all_1['성별']='전체'
        df_all_1['연령']='전체'
    if i == "pc":
        df_all_2 = df_all_i
        df_all_2['유형']='PC'
        df_all_2['성별']='전체'
        df_all_2['연령']='전체'
    if i == "mo":
        df_all_3 = df_all_i
        df_all_3['유형']='MO'
        df_all_3['성별']='전체'
        df_all_3['연령']='전체'
##    
df_list=[df_all_1,df_all_2,df_all_3]
df_all_a=pd.concat(df_list)
df_all_a.drop(["출산/육아"], axis=1, inplace=True)
df_all_a

In [3]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "운동복", "param": [ "50000818"]},
      {"name": "상의", "param": [ "50000803"]},
      {"name": "세트", "param": [ "50000816"]},
      #{"name": "수영복/비치웨어", "param": [ "50004870"]},
      {"name": "아우터", "param": [ "50000806"]},
      {"name": "언더웨어", "param": [ "50000168"]},
      {"name": "잠옷/홈웨어", "param": [ "50000826"]},
      {"name": "하의", "param": [ "50000808"]},
      {"name": "한복", "param": [ "50000819"]},
      {"name": "파티복", "param": [ "50000820"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "패션의류", "param": [ "50000000"]},
      {"name": "원피스", "param": [ "50000807"]},
  ],
  "device":"",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "패션의류")
df_b = change_index(pd.DataFrame(results[1]["data"]), "원피스")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all.drop(["패션의류"], axis=1, inplace=True)
df_all.to_excel("data_mid_09_all.xlsx", sheet_name="click ratio")
df_all.head()

,원피스,운동복,상의,세트,아우터,언더웨어,잠옷/홈웨어,하의,한복,파티복
period,,,,,,,,,,
2021-05-10,7.48706,1.03792,3.91988,0.18236,1.30093,3.82365,1.03295,1.47607,0.18031,0.25655
2021-05-11,7.47142,0.98962,4.00357,0.18822,1.24624,3.80137,1.05664,1.50960,0.17355,0.23965
2021-05-12,7.77586,1.02121,4.33135,0.19717,1.25771,3.86608,0.98787,1.65120,0.17830,0.22912
2021-05-13,8.26052,0.99859,4.56753,0.18664,1.17828,3.86226,1.04392,1.61937,0.16659,0.20737
2021-05-14,8.32612,0.90604,4.42689,0.17195,1.05615,3.90947,1.11255,1.56755,0.16052,0.20613