In [1]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/data

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\data

In [2]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
##종웅님 
headers = {"X-Naver-Client-Id": "EmdlUXsc4CuKNm_kxYKS",
           "X-Naver-Client-Secret":"dSLoIEmMgy"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

In [ ]:
devices=['','pc','mo']

## 대분류 카테고리 설정
for i in devices:
    categories = [
          {"name": "모자", "param": [ "50000181"]},
          {"name": "벨트", "param": [ "50000180"]},
          {"name": "선글라스/안경테", "param": [ "50000183"]},
          {"name": "순금", "param": [ "50000432"]},
          {"name": "시계", "param": [ "50000425"]},
          {"name": "여성신발", "param": [ "50000173"]},
          {"name": "양말", "param": [ "50000166"]},
          {"name": "여행용가방/소품", "param": [ "50000178"]},
          {"name": "장갑", "param": [ "50000551"]},
          {"name": "주얼리", "param": [ "50000189"]},
          {"name": "지갑", "param": [ "50001471"]},
          {"name": "패션소품", "param": [ "50000567"]},
          {"name": "헤어액세서리", "param": [ "50000184"]}
      ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
    data = {
    "startDate": "2021-05-10",
    "endDate": "2023-07-03",
    "timeUnit": "date",
    "category": [
      {"name": "패션잡화", "param": [ "50000001"]},
      {"name": "남성신발", "param": [ "50000174"]},
    ],
    "device":i,
    "gender":"",
    "ages":[]
    }
## 데이터 정제 및 merge 파트
    response = requests.post(url, headers=headers, json=data)

    results = response.json()["results"]


    df_1 = change_index(pd.DataFrame(results[0]["data"]), "패션잡화")
    df_2 = change_index(pd.DataFrame(results[1]["data"]), "남성신발")
##
    df_all_i = pd.merge(df_1, df_2, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
    for category in categories:
        if len(data["category"]) > 2:
            data["category"].pop(2)
        data["category"].append(category)

        result = requests.post(url, headers=headers, json=data)

        results = result.json()["results"]

        df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

        df_all_i = pd.merge(df_all_i, df, left_on="period", right_on="period")
    if i == "":
        df_all_1 = df_all_i
        df_all_1['유형']='PC+MO'
        df_all_1['성별']='전체'
        df_all_1['연령']='전체'
    if i == "pc":
        df_all_2 = df_all_i
        df_all_2['유형']='PC'
        df_all_2['성별']='전체'
        df_all_2['연령']='전체'
    if i == "mo":
        df_all_3 = df_all_i
        df_all_3['유형']='MO'
        df_all_3['성별']='전체'
        df_all_3['연령']='전체'
##    
df_list=[df_all_1,df_all_2,df_all_3]
df_all_a=pd.concat(df_list)
df_all_a.drop(["패션잡화"], axis=1, inplace=True)
df_all_a

In [4]:
categories = [
      {"name": "모자", "param": [ "50000181"]},
      {"name": "벨트", "param": [ "50000180"]},
      {"name": "선글라스/안경테", "param": [ "50000183"]},
      {"name": "순금", "param": [ "50000432"]},
      {"name": "시계", "param": [ "50000425"]},
      {"name": "여성신발", "param": [ "50000173"]},
      {"name": "양말", "param": [ "50000166"]},
      {"name": "여행용가방/소품", "param": [ "50000178"]},
      {"name": "장갑", "param": [ "50000551"]},
      {"name": "주얼리", "param": [ "50000189"]},
      {"name": "지갑", "param": [ "50001471"]},
      {"name": "패션소품", "param": [ "50000567"]},
      {"name": "헤어액세서리", "param": [ "50000184"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "패션잡화", "param": [ "50000001"]},
      {"name": "남성신발", "param": [ "50000174"]},
  ],
  "device":"",
  "gender":"m",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "패션잡화")
df_b = change_index(pd.DataFrame(results[1]["data"]), "남성신발")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all.drop(["패션잡화"], axis=1, inplace=True)
df_all.to_excel("data_mid_10_m.xlsx", sheet_name="click ratio")
df_all.head()

,남성신발,모자,벨트,선글라스/안경테,순금,시계,여성신발,양말,여행용가방/소품,장갑,주얼리,지갑,패션소품,헤어액세서리
period,,,,,,,,,,,,,,
2021-05-10,33.31996,3.79595,1.32090,2.91786,0.08268,0.05641,8.18329,1.41285,0.70407,0.02281,4.10042,0.69630,0.00438,0.37560
2021-05-11,32.05347,3.75816,1.20292,2.85480,0.07910,0.05647,7.67453,1.39562,0.67348,0.02024,3.93198,0.62446,0.00369,0.33806
2021-05-12,31.18791,3.81601,1.24567,2.70404,0.06744,0.04607,7.79696,1.43448,0.67048,0.02501,3.80204,0.54705,0.00257,0.35423
2021-05-13,29.37412,3.66751,1.19741,2.75776,0.06049,0.03980,7.36330,1.43066,0.63098,0.02294,3.56158,0.52310,0.00112,0.34113
2021-05-14,27.13858,3.39327,1.03919,2.44854,0.06055,0.04394,7.20910,1.29745,0.53852,0.02118,3.21537,0.51658,0.00231,0.33592