In [2]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/data

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\data

In [3]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
##종웅님 
headers = {"X-Naver-Client-Id": "EmdlUXsc4CuKNm_kxYKS",
           "X-Naver-Client-Secret":"dSLoIEmMgy"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

In [ ]:
devices=['','pc','mo']

## 대분류 카테고리 설정
for i in devices:
    categories = [
          {"name": "간편조리식품", "param": [ "50000026"]},
          {"name": "김치", "param": [ "50000147"]},
          {"name": "농산물", "param": [ "50000160"]},
          {"name": "반찬", "param": [ "50000147"]},
          {"name": "수산물", "param": [ "50000159"]},
          {"name": "음료", "param": [ "50000148"]},
          {"name": "축산물", "param": [ "50000116"]}
      ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
    data = {
    "startDate": "2021-05-10",
    "endDate": "2023-07-03",
    "timeUnit": "date",
    "category": [
        {"name": "식품", "param": [ "50000006"]},
        {"name": "건강식품", "param": [ "50000030"]},
    ],
    "device":i,
    "gender":"",
    "ages":[]
    }
## 데이터 정제 및 merge 파트
    response = requests.post(url, headers=headers, json=data)

    results = response.json()["results"]


    df_1 = change_index(pd.DataFrame(results[0]["data"]), "식품")
    df_2 = change_index(pd.DataFrame(results[1]["data"]), "건강식품")
##
    df_all_i = pd.merge(df_1, df_2, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
    for category in categories:
        if len(data["category"]) > 2:
            data["category"].pop(2)
        data["category"].append(category)

        result = requests.post(url, headers=headers, json=data)

        results = result.json()["results"]

        df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

        df_all_i = pd.merge(df_all_i, df, left_on="period", right_on="period")
    if i == "":
        df_all_1 = df_all_i
        df_all_1['유형']='PC+MO'
        df_all_1['성별']='전체'
        df_all_1['연령']='전체'
    if i == "pc":
        df_all_2 = df_all_i
        df_all_2['유형']='PC'
        df_all_2['성별']='전체'
        df_all_2['연령']='전체'
    if i == "mo":
        df_all_3 = df_all_i
        df_all_3['유형']='MO'
        df_all_3['성별']='전체'
        df_all_3['연령']='전체'
##    
df_list=[df_all_1,df_all_2,df_all_3]
df_all_a=pd.concat(df_list)
df_all_a.drop(["식품"], axis=1, inplace=True)
df_all_a

In [3]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "간편조리식품", "param": [ "50000026"]},
      {"name": "김치", "param": [ "50000147"]},
      {"name": "농산물", "param": [ "50000160"]},
      {"name": "반찬", "param": [ "50000147"]},
      {"name": "수산물", "param": [ "50000159"]},
      {"name": "음료", "param": [ "50000148"]},
      {"name": "축산물", "param": [ "50000116"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "식품", "param": [ "50000006"]},
      {"name": "건강식품", "param": [ "50000030"]},
  ],
  "device":"",
  "gender":"",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "식품")
df_b = change_index(pd.DataFrame(results[1]["data"]), "건강식품")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all.drop(["식품"], axis=1, inplace=True)
df_all.to_excel("data_mid_07_all.xlsx", sheet_name="click ratio")
df_all.head()

,건강식품,간편조리식품,김치,농산물,반찬,수산물,음료,축산물
period,,,,,,,,
2021-05-10,0.67684,0.56467,0.12903,1.06204,0.12903,0.57227,1.41854,0.12073
2021-05-11,0.62994,0.51511,0.11591,0.98023,0.11591,0.54191,1.34287,0.10028
2021-05-12,0.59334,0.48367,0.11844,0.93441,0.11844,0.55589,1.30079,0.09427
2021-05-13,0.56443,0.44275,0.11434,1.01751,0.11434,0.55153,1.22452,0.08965
2021-05-14,0.51820,0.37545,0.09036,0.80112,0.09036,0.45346,1.14186,0.07736

In [4]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "간편조리식품", "param": [ "50000026"]},
      {"name": "김치", "param": [ "50000147"]},
      {"name": "농산물", "param": [ "50000160"]},
      {"name": "반찬", "param": [ "50000147"]},
      {"name": "수산물", "param": [ "50000159"]},
      {"name": "음료", "param": [ "50000148"]},
      {"name": "축산물", "param": [ "50000116"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "식품", "param": [ "50000006"]},
      {"name": "건강식품", "param": [ "50000030"]},
  ],
  "device":"",
  "gender":"f",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "식품")
df_b = change_index(pd.DataFrame(results[1]["data"]), "건강식품")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all.drop(["식품"], axis=1, inplace=True)
df_all.to_excel("data_mid_07_f.xlsx", sheet_name="click ratio")
df_all.head()

,건강식품,간편조리식품,김치,농산물,반찬,수산물,음료,축산물
period,,,,,,,,
2021-05-10,0.80400,1.14459,0.26289,2.23990,0.26289,0.98838,2.67461,0.30976
2021-05-11,0.75089,1.02330,0.23641,2.05138,0.23641,0.93214,2.52429,0.25411
2021-05-12,0.69054,0.97107,0.23955,1.95079,0.23955,0.94026,2.42278,0.23268
2021-05-13,0.66385,0.86977,0.22714,2.16272,0.22714,0.90995,2.24365,0.22429
2021-05-14,0.59909,0.72990,0.18201,1.65002,0.18201,0.76046,2.00188,0.19179

In [5]:
import requests
import json
import pandas as pd

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR"}

url = "https://openapi.naver.com/v1/datalab/shopping/categories"
## 대분류 카테고리 설정
categories = [
      {"name": "간편조리식품", "param": [ "50000026"]},
      {"name": "김치", "param": [ "50000147"]},
      {"name": "농산물", "param": [ "50000160"]},
      {"name": "반찬", "param": [ "50000147"]},
      {"name": "수산물", "param": [ "50000159"]},
      {"name": "음료", "param": [ "50000148"]},
      {"name": "축산물", "param": [ "50000116"]}
  ]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
  "startDate": "2021-05-10",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": [
      {"name": "식품", "param": [ "50000006"]},
      {"name": "건강식품", "param": [ "50000030"]},
  ],
  "device":"",
  "gender":"m",
  "ages":[]
}
## 데이터 정제 및 merge 파트

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_a = change_index(pd.DataFrame(results[0]["data"]), "식품")
df_b = change_index(pd.DataFrame(results[1]["data"]), "건강식품")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all.drop(["식품"], axis=1, inplace=True)
df_all.to_excel("data_mid_07_m.xlsx", sheet_name="click ratio")
df_all.head()

,건강식품,간편조리식품,김치,농산물,반찬,수산물,음료,축산물
period,,,,,,,,
2021-05-10,5.25190,2.50616,0.51872,4.18303,0.51872,3.32231,6.19389,0.31505
2021-05-11,4.80560,2.26150,0.44831,3.84559,0.44831,3.12470,5.78865,0.24608
2021-05-12,4.52646,2.10371,0.44636,3.66112,0.44636,3.26023,5.65136,0.24036
2021-05-13,4.27107,1.97670,0.45814,3.92503,0.45814,3.23752,5.32907,0.21947
2021-05-14,3.87031,1.65871,0.33080,3.03269,0.33080,2.56778,4.69102,0.20080