In [1]:
%cd C:/Users/sylee/Documents/GitHub/Final_2Kyoungh/Keyword

C:\Users\sylee\Documents\GitHub\Final_2Kyoungh\Keyword

In [2]:
import requests
import json
import pandas as pd
import urllib.request

## 기본 세팅 부분
headers = {"X-Naver-Client-Id": "lJrKhZKFXCGXSoYzh7f7",
           "X-Naver-Client-Secret":"YYPQvTkBxR",
           "Content-Type": "application/json"}

url = "https://openapi.naver.com/v1/datalab/shopping/category/gender"

def change_index(df, column_name):
    df = df.set_index("period")
    df.columns = [column_name]
    return df

In [3]:
data = {
  "startDate": "2023-07-01",
  "endDate": "2023-07-01",
  "timeUnit": "date",
  "category": "50000003",
  "device":"",
  "gender":"",
  "ages":[]
}

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]

results
## 7월 1일 남:여 , 100:84.2, 1.18:1, *** 54.13:45.8

[{'title': '50000003',
  'category': ['50000003'],
  'data': [{'period': '2023-07-01', 'ratio': 84.2251, 'group': 'f'},
   {'period': '2023-07-01', 'ratio': 100, 'group': 'm'}]}]

In [4]:
data = {
  "startDate": "2023-07-02",
  "endDate": "2023-07-02",
  "timeUnit": "date",
  "category": "50000003",
  "device":"",
  "gender":"",
  "ages":[]
}

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]

results
## 100:84.7 1:0.847, 54.14 : 45.86

[{'title': '50000003',
  'category': ['50000003'],
  'data': [{'period': '2023-07-02', 'ratio': 84.78968, 'group': 'f'},
   {'period': '2023-07-02', 'ratio': 100, 'group': 'm'}]}]

In [5]:
data = {
  "startDate": "2023-07-03",
  "endDate": "2023-07-03",
  "timeUnit": "date",
  "category": "50000003",
  "device":"",
  "gender":"",
  "ages":[]
}

response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]

results
## 100:78.85 , 1: 0.788

[{'title': '50000003',
  'category': ['50000003'],
  'data': [{'period': '2023-07-03', 'ratio': 78.8521, 'group': 'f'},
   {'period': '2023-07-03', 'ratio': 100, 'group': 'm'}]}]

In [13]:
df_a = pd.DataFrame(results[0]["data"])
df_a

       period      ratio group
0  2023-07-01   68.34044     f
1  2023-07-01   81.14023     m
2  2023-07-02   76.93324     f
3  2023-07-02   90.73419     m
4  2023-07-03   78.85210     f
5  2023-07-03  100.00000     m

In [12]:
df_a = change_index(pd.DataFrame(results[0]["data"]), "f")
df_b = change_index(pd.DataFrame(results[1]["data"]), "m")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
df_all

ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

In [22]:
df_a = change_index(pd.DataFrame(results[0]["data"]), "모니터")
df_b = change_index(pd.DataFrame(results[1]["data"]), "삼성")
##
df_all = pd.merge(df_a, df_b, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for keyword in keywords:
    if len(data["keyword"]) > 2:
        data["keyword"].pop(2)
    data["keyword"].append(keyword)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), keyword["name"])

    df_all = pd.merge(df_all, df, left_on="period", right_on="period")

df_all

Empty DataFrame
Columns: [모니터, 삼성, 모니터(엘지), 모니터(삼성), 게이밍모니터, 게이밍, 벤큐, LG, LG전자, 삼성전자]
Index: []

In [15]:
## 대분류 카테고리 설정

categories = [
    ## 가전, 전자
    {"name": "생활가전", "param": [ "50001412"]},
    {"name": "영상가전", "param": [ "50000208"]},
    {"name": "이미용가전", "param": [ "50000211"]},
    {"name": "주방가전", "param": [ "50000213"]},
    {"name": "계절가전", "param": [ "50000212"]},
    {"name": "카메라/캠코더용품", "param": [ "50000152"]},
        
    ## 컴퓨터 및 주변기기
    {"name": "PC", "param": [ "50000089"]},
    {"name": "PC부품", "param": [ "50000097"]},
    {"name": "PC액세서리", "param": [ "50000090"]},
    {"name": "저장장치", "param": [ "50000096"]},
    {"name": "멀티미디어장비", "param": [ "50000095"]},
    {"name": "모니터", "param": [ "50000153"]},
    {"name": "모니터주변기기", "param": [ "50000093"]},
    {"name": "노트북", "param": [ "50000151"]},
    {"name": "노트북액세서리", "param": [ "50000091"]},
    {"name": "소프트웨어", "param": [ "50000099"]},
    {"name": "주변기기", "param": [ "50000094"]},
        
    ## 통신기기
    {"name": "음향가전", "param": [ "50000209"]},
    {"name": "태블릿PC", "param": [ "50000152"]},
    {"name": "태블릿PC액세서리", "param": [ "50000092"]},
        
    ## 기타
    {"name": "자동차기기", "param": [ "50000214"]},
    {"name": "게임기/타이틀", "param": [ "50000088"]},        
    {"name": "광학기기/용품", "param": [ "50000207"]},        
    {"name": "학습기기", "param": [ "50000087"]}]
## API 요청 값 작성, 디지털/가전 = result[0], 패션의류 = result[1]
data = {
    "startDate": "2021-05-10",
    "endDate": "2023-07-03",
    "timeUnit": "date",
    "category": [
      {"name": "디지털/가전", "param": [ "50000003"]},
      {"name": "휴대폰액세서리", "param": [ "50000205"]},
    ],
    "device":"",
    "gender":"",
    "ages":["20"]
}
## 데이터 정제 및 merge 파트
response = requests.post(url, headers=headers, json=data)

results = response.json()["results"]


df_1 = change_index(pd.DataFrame(results[0]["data"]), "디지털/가전")
df_2 = change_index(pd.DataFrame(results[1]["data"]), "휴대폰액세서리")
##
df_all_i = pd.merge(df_1, df_2, left_on="period", right_on="period")
## 반복문 통해서 카테고리에 설정된 값, 불러오고 저장, 합치기
for category in categories:
    if len(data["category"]) > 2:
        data["category"].pop(2)
    data["category"].append(category)

    result = requests.post(url, headers=headers, json=data)

    results = result.json()["results"]

    df = change_index(pd.DataFrame(results[2]["data"]), category["name"])

    df_all_i = pd.merge(df_all_i, df, left_on="period", right_on="period")

df_all_a.drop(["디지털/가전"], axis=1, inplace=True)
df_all_a

,휴대폰액세서리,생활가전,영상가전,이미용가전,주방가전,계절가전,카메라/캠코더용품,PC,PC부품,PC액세서리,...,음향가전,태블릿PC,태블릿PC액세서리,자동차기기,게임기/타이틀,광학기기/용품,학습기기,유형,성별,연령
period,,,,,,,,,,,,,,,,,,,,,
2021-05-10,6.04648,0.10834,1.05858,1.49650,4.13670,2.30338,0.88026,0.30601,0.92371,0.63326,...,4.75753,0.88026,1.17055,0.44029,1.62722,0.03944,0.07397,PC+MO,전체,20
2021-05-11,5.69324,0.09456,0.91425,1.36849,3.71780,2.13457,0.72469,0.29887,0.91436,0.62764,...,4.20387,0.72469,1.09446,0.39684,1.42468,0.03479,0.05949,PC+MO,전체,20
2021-05-12,5.48206,0.08375,0.86146,1.28997,3.52830,2.45366,0.75878,0.28596,0.92770,0.58597,...,4.01874,0.75878,1.04437,0.38025,1.32218,0.03144,0.06187,PC+MO,전체,20
2021-05-13,5.01507,0.07943,0.79634,1.23031,3.30631,3.78778,0.64709,0.28693,0.85919,0.54058,...,3.74444,0.64709,0.92360,0.38820,1.26328,0.03782,0.05587,PC+MO,전체,20
2021-05-14,4.58375,0.06619,0.72355,1.12440,2.98074,4.77223,0.63293,0.24867,0.77359,0.48833,...,3.39126,0.63293,0.81909,0.32157,1.14618,0.02745,0.04938,PC+MO,전체,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-29,3.33621,0.05339,0.51016,0.78659,1.46020,2.48462,0.27436,0.09540,0.45252,0.31476,...,1.73601,0.27436,0.50165,0.22482,0.80608,0.03224,0.05384,MO,전체,20
2023-06-30,2.98444,0.05166,0.44861,0.71705,1.29705,2.12066,0.25241,0.08528,0.39798,0.30074,...,1.58911,0.25241,0.45246,0.20649,0.85090,0.02816,0.04609,MO,전체,20
2023-07-01,3.48052,0.07155,0.54464,0.81970,1.53411,2.46358,0.30327,0.09815,0.40350,0.28907,...,1.79060,0.30327,0.49401,0.22011,0.90412,0.03712,0.05074,MO,전체,20
2023-07-02,4.01753,0.07925,0.62366,0.98217,1.75486,2.89685,0.31419,0.11746,0.40137,0.31654,...,1.95393,0.31419,0.57648,0.25212,0.96510,0.03810,0.05787,MO,전체,20
2023-07-03,3.75098,0.07597,0.55752,0.91918,1.65951,3.34547,0.28798,0.11005,0.47045,0.34419,...,1.91192,0.28798,0.53562,0.24787,0.92314,0.04155,0.05856,MO,전체,20